### ISSUE TITLE
crash on 1.20.2

### ISSUE THREAD

**Issue by AAOYokohama** [gbl/DurabilityViewer#100] opened 2023-09-27 18:19 UTC
game crashes everytime related to cardinal components looks like, im on fabric
[crash-2023-09-27_11.52.15-client.txt](https://github.com/gbl/DurabilityViewer/files/12741912/crash-2023-09-27_11.52.15-client.txt)

**Comment by gbl** [comment] 2023-09-28 06:01
Going to look into this, but I'm on vacation right now, so I won't be able to check until mid October.

**Comment by TheMrEngMan** [comment] 2023-09-29 17:41
Fixed by #101

**Comment by bendvis** [comment] 2023-10-07 16:34
I was experiencing crashing on single player level load.  Pulled down TheMrEngMan's build and made sure Cloth Config was up to date.  Confirmed fixed.

**Comment by Crypthammer** [comment] 2023-11-21 08:18
Still getting a crash with the fabric version of this mod (haven't tested the forge version because I don't use forge).  Any update at all?

**Comment by TheMrEngMan** [comment] 2023-11-30 00:34
> Still getting a crash with the fabric version of this mod (haven't tested the forge version because I don't use forge). Any update at all?

This is fixed in #101, @gbl just has not had the opportunity to merge yet

**Comment by gbl** [comment] 2023-12-13 16:11
There's a 1.20.4 version out now.

**Closed as completed by gbl** 2023-12-13 16:11 UTC
