### ISSUE TITLE
[Bug] The game crashes while loading.

### ISSUE THREAD

**Issue by ZiuChen** [gbl/DurabilityViewer#62] opened 2021-12-01 14:21 UTC
The game crashes while loading.

Game Crash Report:
> Missing: net/fabricmc/fabric/api/client/keybinding/KeyBindingRegistry

> Game Version: 1.18
> Mod Version: durabilityviewer-1.18-fabric0.43.1-1.10.2
> Fabric Version: 0.12.7
> Fabric API Version: 0.43.1

The mod is excellent, please fix it as soon as possible!

**Comment by gbl** [comment] 2021-12-01 17:36
Hm, it doesn't do that for me. Please post a complete crash log. This sounds like the game doesn't find Fabric API.

**Comment by ZiuChen** [comment] 2021-12-02 01:31
After removing DurabilityViewer mod, other mods can be loaded and used normally.
Here is my mods list.

> ![image](https://user-images.githubusercontent.com/64892985/144341045-1de9fd1f-dab2-44dd-974a-280ded691ef7.png)

Here is my game crash log.
> [minecraft-exported-logs](https://pastebin.com/nuKQXB9L)
    password: c6wLuM44bA

Thank you!

**Comment by gbl** [comment] 2021-12-02 08:08
The log is still incomplete, there's some stuff missing from the top which should look like this:

```
[08:57:16] [main/INFO]: Loading for game Minecraft 1.18
[08:57:16] [main/INFO]: Loading 77 mods:
	- advancementinfo 1.18-fabric0.43.1-1.3
	- antighost 1.18-fabric0.43.1-1.1.4
...
	- worldtime 1.18-fabric0.43.1-1.3.1
[08:57:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/gbl/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT

```

but there's something very wrong with your installation. All the java.lang.IllegalArgumentException: `Unsupported class file major version 61` errors mean some component is expecting Java 16 and doesn't work with Java 17. Also, you're not using the newest loader (0.12.8), maybe it has something to do with that. Try installing the Fabric loader, and if the problem persists, send me a *complete* crash log.

**Comment by ZiuChen** [comment] 2021-12-02 14:05
I updated my Fabric version to 0.12.8, but it still reports an error.
Here is my full game crash log. Thanks alot!
> [latest.log](https://pastebin.com/jaR31c2G)
> password: 4VsSXg9WtG

**Comment by gbl** [comment] 2021-12-02 15:15
Oh that's interesting. It looks like for some reason your Fabric API gets loaded from sodium, instead of the API itself.

Your "loading mods" says:
```
	- fabric 0.43.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cd14 via sodium
	- fabric-rendering-data-attachment-v1 0.3.3+d154e2c614 via sodium
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9514 via sodium
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via sodium
	- fabricloader 0.12.8
```

while mine (which doesn't have sodium) says
```
	- fabric 0.43.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cd14 via fabric
	- fabric-api-lookup-api-v1 1.3.5+3ac43d9514 via fabric
	- fabric-biome-api-v1 6.0.1+3ac43d9514 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9514 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9514 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd14 via fabric
	- fabric-containers-v0 0.1.18+d154e2c614 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d14 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9514 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957114 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a14 via fabric
	- fabric-events-interaction-v0 0.4.15+3ac43d9514 via fabric
	- fabric-events-lifecycle-v0 0.2.5+b4f4f6cd14 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9514 via fabric
	- fabric-item-api-v1 1.2.7+3ac43d9514 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9514 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f314 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd14 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca33514 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9514 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9514 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd14 via fabric
	- fabric-models-v0 0.3.3+3ac43d9514 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9514 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd14 via fabric
	- fabric-object-builder-api-v1 1.10.13+3ac43d9514 via fabric
	- fabric-object-builders-v0 0.7.7+3ac43d9514 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac14 via fabric
	- fabric-registry-sync-v0 0.8.5+3ac43d9514 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9514 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9514 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd14 via fabric
	- fabric-rendering-data-attachment-v1 0.3.3+d154e2c614 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9514 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd14 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a14 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9514 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9514 via fabric
	- fabric-structure-api-v1 2.0.8+295197a714 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9514 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9514 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5514 via fabric
	- fabric-transfer-api-v1 1.5.4+b4f4f6cd14 via fabric
	- fabricloader 0.12.8
```

As you see, there's lots of components that get loaded in my installation ("via fabric") which don't in yours ("via sodium").

This almost looks like a fabric loader bug to me. I'll check this with the Fabric discord and maybe open a PR there. The version update from 0.12.7 to 0.12.8 should have fixed exactly that bug.

Or maybe the old loader got it wrong but wrote the info to the cache folder, and the new one is still using the old cache. Your mods folder should have a ".fabric" subfolder; try removing that completely (while the game isn't running). Maybe that helps.

Otherwise, you might try 
a) not using sodium
b) using the sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar from curseforge, your's is named differently so it might be a bug in that version that's fixed by now
c) using a zip viewer like 7z and removing the META-INF/jars/fabric-*.jar files from the sodium jar; maybe fabric will take them from the api itself if they're not present somewhere else any more.

**Comment by ZiuChen** [comment] 2021-12-03 03:02
I reinstalled a version that only had Fabric and DurabilityViewer.
When I enable DurabilityViewer, the game crashes.
I checked the error report. Looks like login information verification failed.
But with DurabilityViewer disabled, the game starts normally.

If someone else doesn't encounter this situation, it must be my mistake.
Thank you very much for your suggestions. I will continue to provide bug reports if necessary.
Again, thank you very much!

> [Normal start log](https://pastebin.com/9VKhmzrz)
> password: JYzJM9QeH5

> [Crash log](https://pastebin.com/X7XcbmN1)
> password: Wq1UzL71Q6

**Comment by gbl** [comment] 2021-12-03 08:39
Sorry, I'm afraid I can't help you much here. I can't see anything in the logs that hints at the cause of the crash. There are almost 1000 downloads on Curseforge, and noone else is reporting the same bug, so something must be very specific to your installation. But I can't see what that is, in the logs.

**Closed as completed** 2023-06-29 08:11 UTC
